[project]
name = "nimverta-website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
    "django>=5.2.4",
    "django-markdownify>=0.9.5",
    "django-tailwind>=4.2.0",
]
